.PHONY : all
all : assignment2 test

assignment2 : assignment2.c
	echo "\nBuilding assignment2\n"
	gcc -o assignment2 assignment2.c -lm -O2

test : test.c
	echo "\nBuilding test\n"
	gcc -o test test.c -lm -O2
