.PHONY : all
all : fwrite_fread

fwrite_fread : fwrite_fread.c
	echo "\nBuilding fwrite_fread\n"
	gcc -o fwrite_fread fwrite_fread.c -O2

fprintf_fscanf : fprintf_fscanf.c
	echo "\nBuilding fprintf_fscanf\n"
	gcc -o fprintf_fscanf fprintf_fscanf.c -O2
